name: Deploy Pages

on:
  push:
    branches: ["main"]
    paths:
      [
        "pages/**/*.js",
        "pages/**/*.css",
        "pages/**/*.html",
        "pages/**/*.svg",
        "pages/**/*.json",
        "pages/**/*.ts",
        "pages/**/*.tsx",
        "pages/**/*.sh",
      ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Build
        run: bash ./scripts/build.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
